//go:build cgo

package gstreamer

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"math"

	"github.com/mengelbart/mrtp/media"
)

func init() {
	media.Register("gst", &factory{})
}

type factory struct {
	ccfb   bool
	scream bool

	udp             bool
	udpLocal        string
	udpRemote       string
	udpRTPPort      uint
	udpRTCPSendPort uint
	udpRTCPRecvPort uint
	udpRecvBuffer   int
	udpTraceRTP     bool
}

// ConfigureFlags implements media.Factory.
func (f *factory) ConfigureFlags(fs *flag.FlagSet) {
	fs.BoolVar(&f.ccfb, "gst-ccfb", false,
		"Send CCFB RTCP feedback packets generated by the screamrx element")
	fs.BoolVar(&f.scream, "gst-scream", false,
		"Run SCReAM congestion control in the pipeline, using the screamtx element")

	fs.BoolVar(&f.udp, "gst-udp", false,
		"Move RTP and RTCP with GStreamer's own udpsink and udpsrc elements. The command's transport and address flags are then unused: the addresses come from the -gst-udp-* flags below.")
	fs.StringVar(&f.udpLocal, "gst-udp-local", "127.0.0.1",
		"Local address to receive on with -gst-udp")
	fs.StringVar(&f.udpRemote, "gst-udp-remote", "127.0.0.1",
		"Remote address to send to with -gst-udp")
	fs.UintVar(&f.udpRTPPort, "gst-udp-rtp-port", 5000,
		"UDP port of the RTP stream with -gst-udp")
	fs.UintVar(&f.udpRTCPSendPort, "gst-udp-rtcp-send-port", 0,
		"UDP port for outgoing RTCP with -gst-udp. 0, the default, derives it from the RTP port.")
	fs.UintVar(&f.udpRTCPRecvPort, "gst-udp-rtcp-recv-port", 0,
		"UDP port for incoming RTCP with -gst-udp. 0, the default, derives it from the RTP port.")
	fs.IntVar(&f.udpRecvBuffer, "gst-udp-recv-buffer-size", 0,
		"Size of the UDP receive buffer in bytes with -gst-udp, 0 leaves the operating system default")
	fs.BoolVar(&f.udpTraceRTP, "gst-udp-trace-rtp", false,
		"Log the RTP packets passing the udpsink and udpsrc elements of -gst-udp")
}

// NewPipeline implements media.Factory.
func (f *factory) NewPipeline() (media.Pipeline, error) {
	if f.udp {
		for name, port := range map[string]uint{
			"gst-udp-rtp-port":       f.udpRTPPort,
			"gst-udp-rtcp-send-port": f.udpRTCPSendPort,
			"gst-udp-rtcp-recv-port": f.udpRTCPRecvPort,
		} {
			if port > math.MaxUint16 {
				return nil, fmt.Errorf("invalid -%v value %v", name, port)
			}
		}
	}
	bin, err := NewRTPBin()
	if err != nil {
		return nil, err
	}
	return &pipeline{factory: f, bin: bin}, nil
}

// rtcpPorts returns the RTCP ports of one stream. An unset port is derived
// from the RTP port, mirrored between the two directions so that a sender and
// a receiver started with the same flags talk to each other: the sender's
// outgoing RTCP arrives on the port the receiver listens on.
func (f *factory) rtcpPorts(sending bool) (send, recv uint) {
	send, recv = f.udpRTCPSendPort, f.udpRTCPRecvPort
	sendOffset, recvOffset := uint(1), uint(2)
	if !sending {
		sendOffset, recvOffset = 2, 1
	}
	if send == 0 {
		send = f.udpRTPPort + sendOffset
	}
	if recv == 0 {
		recv = f.udpRTPPort + recvOffset
	}
	return send, recv
}

// errNoRTPEndpoint is returned for a stream that has neither an RTP endpoint to
// read or write nor -gst-udp to move the packets itself, which is what asking
// for -transport gst-udp without -gst-udp looks like from here.
var errNoRTPEndpoint = errors.New("stream has no RTP endpoint, and the pipeline was not given -gst-udp")

// pipeline adapts RTPBin to media.Pipeline.
type pipeline struct {
	factory *factory
	bin     *RTPBin
	nextID  int
}

// AddSender implements media.Pipeline.
func (p *pipeline) AddSender(config media.SenderConfig) (media.Sender, error) {
	options := []StreamSourceOption{
		StreamSourceCodec(config.Codec),
		StreamSourcePayloadType(config.PayloadType),
	}
	if config.SourceLocation != media.SourceTest {
		options = append(options,
			StreamSourceType(Filesrc),
			StreamSourceFileSourceLocation(config.SourceLocation),
		)
	}
	source, err := NewStreamSource(config.Name, options...)
	if err != nil {
		return nil, err
	}

	id := p.claimID()

	// The transport has to be known before the stream is added: adding the
	// stream requests the pad that the transport is linked to.
	if err = p.addRTPSink(id, config.RTP); err != nil {
		return nil, err
	}
	if p.factory.scream {
		bounds := config.RateBounds
		if err = p.bin.EnableSCReAM(bounds.Initial/1000, bounds.Min/1000, bounds.Max/1000); err != nil {
			return nil, err
		}
		p.bin.SetTargetRateEncoder = source.SetBitrate
	}
	if err = p.bin.addRTPSourceStream(id, source); err != nil {
		return nil, err
	}
	if err = p.addRTCP(id, config.RTCP, true); err != nil {
		return nil, err
	}
	return &sender{source: source}, nil
}

// AddReceiver implements media.Pipeline.
func (p *pipeline) AddReceiver(config media.ReceiverConfig) error {
	sinkType, location := Autovideosink, ""
	switch config.SinkLocation {
	case media.SinkDisplay:
	case media.SinkDiscard:
		sinkType = Fakesink
	default:
		sinkType, location = Filesink, config.SinkLocation
	}

	sink, err := NewStreamSink(config.Name,
		StreamSinkCodec(config.Codec),
		StreamSinkType(sinkType),
		StreamSinkLocation(location),
		StreamSinkPayloadType(config.PayloadType),
	)
	if err != nil {
		return err
	}

	id := p.claimID()
	if err = p.bin.addRTPSinkStream(id, sink); err != nil {
		return err
	}
	if err = p.addRTPSource(id, config.RTP); err != nil {
		return err
	}
	return p.addRTCP(id, config.RTCP, false)
}

// Run implements media.Pipeline.
func (p *pipeline) Run(ctx context.Context) error {
	stopped := make(chan struct{})
	defer close(stopped)
	go func() {
		select {
		case <-ctx.Done():
			if stopErr := p.bin.stop(); stopErr != nil {
				slog.Error("failed to stop media pipeline", "error", stopErr)
			}
		case <-stopped:
		}
	}()
	return p.bin.Run()
}

// Close implements media.Pipeline.
func (p *pipeline) Close() error {
	return p.bin.stop()
}

func (p *pipeline) claimID() int {
	id := p.nextID
	p.nextID++
	return id
}

func (p *pipeline) addRTPSink(id int, writer io.WriteCloser) error {
	if p.factory.udp {
		sink, err := newUDPSinkElement(p.factory.udpRemote, p.factory.udpRTPPort, p.factory.udpTraceRTP)
		if err != nil {
			return err
		}
		return p.bin.addRTPTransportSinkElement(id, sink)
	}
	if writer == nil {
		return errNoRTPEndpoint
	}
	return p.bin.AddRTPTransportSink(id, writer)
}

func (p *pipeline) addRTPSource(id int, reader io.ReadCloser) error {
	if p.factory.udp {
		source, err := newUDPSrcElement(p.factory.udpLocal, p.factory.udpRTPPort,
			p.factory.udpTraceRTP, p.factory.udpRecvBuffer)
		if err != nil {
			return err
		}
		return p.bin.receiveRTPStreamFromElement(id, source, p.factory.ccfb)
	}
	if reader == nil {
		return errNoRTPEndpoint
	}
	return p.bin.ReceiveRTPStreamFrom(id, reader, p.factory.ccfb)
}

// addRTCP attaches the RTCP flow of one stream. sending tells the two
// directions apart, which only matters for the ports the pipeline's own UDP
// elements use, see factory.rtcpPorts.
func (p *pipeline) addRTCP(id int, flow media.RTCPFlow, sending bool) error {
	if p.factory.udp {
		return p.addUDPRTCP(id, sending)
	}
	if flow.Send != nil {
		if err := p.bin.SendRTCPForStream(id, flow.Send); err != nil {
			return err
		}
	}
	if flow.Recv != nil {
		return p.bin.ReceiveRTCPFrom(flow.Recv)
	}
	return nil
}

func (p *pipeline) addUDPRTCP(id int, sending bool) error {
	sendPort, recvPort := p.factory.rtcpPorts(sending)
	sink, err := newUDPSinkElement(p.factory.udpRemote, sendPort, false)
	if err != nil {
		return err
	}
	if err = p.bin.sendRTCPForStreamElement(id, sink); err != nil {
		return err
	}
	source, err := newUDPSrcElement(p.factory.udpLocal, recvPort, false, 0)
	if err != nil {
		return err
	}
	return p.bin.receiveRTCPFromElement(source)
}

// sender adapts StreamSource to media.Sender.
type sender struct {
	source *StreamSource
}

// SetTargetBitrate implements media.Sender.
func (s *sender) SetTargetBitrate(bitrate uint) error {
	return s.source.SetBitrate(bitrate)
}
