//go:build cgo

package gstreamer

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"math"
	"sync/atomic"

	"github.com/mengelbart/mrtp"
	"github.com/mengelbart/mrtp/media"
	"github.com/mengelbart/mrtp/pipeline"
)

func init() {
	media.Register("gst", &implementation{})
}

type implementation struct {
	ccfb   bool
	scream bool

	udp             bool
	udpLocal        string
	udpRemote       string
	udpRTPPort      uint
	udpRTCPSendPort uint
	udpRTCPRecvPort uint
	udpRecvBuffer   int
	udpTraceRTP     bool
}

// ConfigureFlags implements media.Implementation.
func (f *implementation) ConfigureFlags(fs *flag.FlagSet) {
	fs.BoolVar(&f.ccfb, "gst-ccfb", false,
		"Send CCFB RTCP feedback packets generated by the screamrx element")
	fs.BoolVar(&f.scream, "gst-scream", false,
		"Run SCReAM congestion control in the pipeline, using the screamtx element")

	fs.BoolVar(&f.udp, "gst-udp", false,
		"Move RTP and RTCP with GStreamer's own udpsink and udpsrc elements. The command's transport and address flags are then unused: the addresses come from the -gst-udp-* flags below.")
	fs.StringVar(&f.udpLocal, "gst-udp-local", "127.0.0.1",
		"Local address to receive on with -gst-udp")
	fs.StringVar(&f.udpRemote, "gst-udp-remote", "127.0.0.1",
		"Remote address to send to with -gst-udp")
	fs.UintVar(&f.udpRTPPort, "gst-udp-rtp-port", 5000,
		"UDP port of the RTP stream with -gst-udp")
	fs.UintVar(&f.udpRTCPSendPort, "gst-udp-rtcp-send-port", 0,
		"UDP port for outgoing RTCP with -gst-udp. 0, the default, derives it from the RTP port.")
	fs.UintVar(&f.udpRTCPRecvPort, "gst-udp-rtcp-recv-port", 0,
		"UDP port for incoming RTCP with -gst-udp. 0, the default, derives it from the RTP port.")
	fs.IntVar(&f.udpRecvBuffer, "gst-udp-recv-buffer-size", 0,
		"Size of the UDP receive buffer in bytes with -gst-udp, 0 leaves the operating system default")
	fs.BoolVar(&f.udpTraceRTP, "gst-udp-trace-rtp", false,
		"Log the RTP packets passing the udpsink and udpsrc elements of -gst-udp")
}

// NewFactory implements media.Implementation.
func (f *implementation) NewFactory() (media.Factory, error) {
	if f.udp {
		for name, port := range map[string]uint{
			"gst-udp-rtp-port":       f.udpRTPPort,
			"gst-udp-rtcp-send-port": f.udpRTCPSendPort,
			"gst-udp-rtcp-recv-port": f.udpRTCPRecvPort,
		} {
			if port > math.MaxUint16 {
				return nil, fmt.Errorf("invalid -%v value %v", name, port)
			}
		}
	}
	bin, err := NewRTPBin()
	if err != nil {
		return nil, err
	}
	shared := pipeline.NewGraph()
	// The bin's main loop is what the whole pipeline runs on, so the graph
	// carrying it ends the run when it stops.
	shared.Terminal(&binDriver{bin: bin})
	return &factory{impl: f, bin: bin, shared: shared}, nil
}

// udpRTCPPorts returns the RTCP ports of one stream with -gst-udp. An unset port is derived
// from the RTP port, mirrored between the two directions so that a sender and
// a receiver started with the same flags talk to each other: the sender's
// outgoing RTCP arrives on the port the receiver listens on.
func (f *implementation) udpRTCPPorts(sending bool) (send, recv uint) {
	send, recv = f.udpRTCPSendPort, f.udpRTCPRecvPort
	sendOffset, recvOffset := uint(1), uint(2)
	if !sending {
		sendOffset, recvOffset = 2, 1
	}
	if send == 0 {
		send = f.udpRTPPort + sendOffset
	}
	if recv == 0 {
		recv = f.udpRTPPort + recvOffset
	}
	return send, recv
}

// factory builds the streams of one RTPBin. The bin outlives them, and its
// main loop is what carries them, so it lives in the shared graph.
type factory struct {
	impl   *implementation
	bin    *RTPBin
	shared *pipeline.Graph

	nextID atomic.Int64
}

// Shared implements media.Factory.
func (f *factory) Shared() *pipeline.Graph {
	return f.shared
}

// binDriver runs the bin's GStreamer main loop as a pipeline element.
type binDriver struct {
	bin *RTPBin
}

// Run implements mrtp.Driver.
func (d *binDriver) Run(ctx context.Context) error {
	stopped := make(chan struct{})
	defer close(stopped)
	go func() {
		select {
		case <-ctx.Done():
			if err := d.bin.stop(); err != nil {
				slog.Error("failed to stop media pipeline", "error", err)
			}
		case <-stopped:
		}
	}()
	return d.bin.Run()
}

// Close implements mrtp.Element.
func (d *binDriver) Close() error {
	return d.bin.stop()
}

// NewSender implements media.Factory.
func (f *factory) NewSender(config media.SenderConfig) (*media.SendStream, error) {
	options := []StreamSourceOption{
		StreamSourceCodec(config.Codec),
		StreamSourcePayloadType(config.PayloadType),
	}
	if config.SourceLocation != media.SourceTest {
		options = append(options,
			StreamSourceType(Filesrc),
			StreamSourceFileSourceLocation(config.SourceLocation),
		)
	}
	source, err := NewStreamSource(config.Name, options...)
	if err != nil {
		return nil, err
	}

	id := f.claimID()
	stream := &media.SendStream{Graph: pipeline.NewGraph(), Sender: &sender{source: source}}

	// The transport has to be known before the stream is added: adding the
	// stream requests the pad that the transport is linked to.
	if stream.RTP, err = f.rtpOutput(id, config); err != nil {
		return nil, err
	}
	if f.impl.scream {
		bounds := config.RateBounds
		if err = f.bin.EnableSCReAM(bounds.Initial/1000, bounds.Min/1000, bounds.Max/1000); err != nil {
			return nil, err
		}
		f.bin.SetTargetRateEncoder = source.SetBitrate
	}
	if err = f.bin.addRTPSourceStream(id, source); err != nil {
		return nil, err
	}
	if stream.RTCP, stream.Feedback, err = f.rtcpPorts(id, true); err != nil {
		return nil, err
	}
	return stream, nil
}

// NewReceiver implements media.Factory.
func (f *factory) NewReceiver(config media.ReceiverConfig) (*media.ReceiveStream, error) {
	sinkType, location := Autovideosink, ""
	switch config.SinkLocation {
	case media.SinkDisplay:
	case media.SinkDiscard:
		sinkType = Fakesink
	default:
		sinkType, location = Filesink, config.SinkLocation
	}

	sink, err := NewStreamSink(config.Name,
		StreamSinkCodec(config.Codec),
		StreamSinkType(sinkType),
		StreamSinkLocation(location),
		StreamSinkPayloadType(config.PayloadType),
	)
	if err != nil {
		return nil, err
	}

	id := f.claimID()
	if err = f.bin.addRTPSinkStream(id, sink); err != nil {
		return nil, err
	}
	stream := &media.ReceiveStream{Graph: pipeline.NewGraph()}
	if stream.RTP, err = f.rtpInput(id); err != nil {
		return nil, err
	}
	if stream.RTCP, stream.Feedback, err = f.rtcpPorts(id, false); err != nil {
		return nil, err
	}
	return stream, nil
}

func (f *factory) claimID() int {
	return int(f.nextID.Add(1) - 1)
}

// rtpOutput is the port a stream's RTP leaves on, or nil with -gst-udp, where
// the bin sends the packets itself.
func (f *factory) rtpOutput(id int, config media.SenderConfig) (mrtp.Source[mrtp.RTPPacket], error) {
	if f.impl.udp {
		sink, err := newUDPSinkElement(f.impl.udpRemote, f.impl.udpRTPPort, f.impl.udpTraceRTP)
		if err != nil {
			return nil, err
		}
		return nil, f.bin.addRTPTransportSinkElement(id, sink)
	}
	format, err := media.RTPFormat(config.Codec, config.PayloadType)
	if err != nil {
		return nil, err
	}
	return f.bin.rtpOutput(id, format)
}

// rtpInput is the port a stream's RTP enters on, or nil with -gst-udp, where
// the bin receives the packets itself.
func (f *factory) rtpInput(id int) (mrtp.Sink[mrtp.RTPPacket], error) {
	if f.impl.udp {
		src, err := newUDPSrcElement(f.impl.udpLocal, f.impl.udpRTPPort,
			f.impl.udpTraceRTP, f.impl.udpRecvBuffer)
		if err != nil {
			return nil, err
		}
		return nil, f.bin.receiveRTPStreamFromElement(id, src, f.impl.ccfb)
	}
	return f.bin.rtpInput(id, f.impl.ccfb)
}

// rtcpPorts are the RTCP ports of one stream, or nil with -gst-udp, where the
// bin moves the packets itself. sending tells the two directions apart, which
// only matters for the ports those UDP elements use, see
// implementation.udpRTCPPorts.
func (f *factory) rtcpPorts(id int, sending bool) (mrtp.Source[mrtp.RTCPPacket], mrtp.Consumer[mrtp.RTCPPacket], error) {
	if f.impl.udp {
		return nil, nil, f.addUDPRTCP(id, sending)
	}
	out, err := f.bin.rtcpOutput(id)
	if err != nil {
		return nil, nil, err
	}
	in, err := f.bin.rtcpInput()
	if err != nil {
		return nil, nil, err
	}
	return out, in, nil
}

func (f *factory) addUDPRTCP(id int, sending bool) error {
	sendPort, recvPort := f.impl.udpRTCPPorts(sending)
	sink, err := newUDPSinkElement(f.impl.udpRemote, sendPort, false)
	if err != nil {
		return err
	}
	if err = f.bin.sendRTCPForStreamElement(id, sink); err != nil {
		return err
	}
	source, err := newUDPSrcElement(f.impl.udpLocal, recvPort, false, 0)
	if err != nil {
		return err
	}
	return f.bin.receiveRTCPFromElement(source)
}

// sender adapts StreamSource to media.Sender.
type sender struct {
	source *StreamSource
}

// SetTargetBitrate implements media.Sender.
func (s *sender) SetTargetBitrate(bitrate uint) error {
	return s.source.SetBitrate(bitrate)
}
