package subcmd

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"math"
	"os"
	"time"

	"github.com/mengelbart/mrtp"
	"github.com/mengelbart/mrtp/cmdmain"
	"github.com/mengelbart/mrtp/data"
	"github.com/mengelbart/mrtp/flags"
	"github.com/mengelbart/mrtp/gstreamer"
	"github.com/mengelbart/mrtp/internal/quictransport"
	"github.com/mengelbart/mrtp/roq"
	roqProtocol "github.com/mengelbart/roq"
	"github.com/quic-go/quic-go"
)

func init() {
	cmdmain.RegisterSubCmd("receive", func() cmdmain.SubCmd { return new(Receive) })
}

// UDPRecvBufferSize is the default UDP Receive Buffer size for the Gstreamer
// udpsrc element
var UDPRecvBufferSize int

type StreamSinkFactory interface {
	ConfigureFlags(*flag.FlagSet)
	MakeStreamSink(name string, payloadType int) (gstreamer.RTPSinkBin, error)
}

type gstreamerVideoStreamSinkFactory struct {
	sinkType     uint
	sinkLocation string
	codec        string
}

func (f *gstreamerVideoStreamSinkFactory) ConfigureFlags(fs *flag.FlagSet) {
	fs.UintVar(&f.sinkType, "sink-type", uint(0), "Sink type (0: autovideosink, 1: filesink, requires <location> to be set, 2: fakesink)")
	fs.StringVar(&f.sinkLocation, "sink-location", "", "Location for filesink (if <sink-type> is 1 (filesink))")

	// check if codec flag is already registered - relevant for webrtc subcmd
	if fs.Lookup("codec") == nil {
		fs.StringVar(&f.codec, "codec", mrtp.H264.String(), "Codec to use (H264, VP8)")
	}
}

func (f *gstreamerVideoStreamSinkFactory) MakeStreamSink(name string, pt int) (gstreamer.RTPSinkBin, error) {
	if f.sinkType == uint(gstreamer.Filesink) && len(f.sinkLocation) == 0 {
		return nil, errors.New("file-sink requires a location to be set via the -sink-location flag")
	}

	codec, error := mrtp.NewCodec(f.codec)
	if error != nil {
		return nil, error
	}

	return gstreamer.NewStreamSink(
		name,
		gstreamer.StreamSinkCodec(codec),
		gstreamer.StreamSinkType(gstreamer.SinkType(f.sinkType)),
		gstreamer.StreamSinkLocation(f.sinkLocation),
		gstreamer.StreamSinkPayloadType(pt),
	)
}

var DefaultStreamSinkFactory StreamSinkFactory = &gstreamerVideoStreamSinkFactory{}

type Receive struct {
	localAddr    string
	remoteAddr   string
	receiver     *gstreamer.RTPBin
	sink         gstreamer.RTPSinkBin
	roqMapping   uint
	roqServer    bool
	roqClient    bool
	gstCCFB      bool
	qlog         bool
	nadaFeedback bool
	traceRTP     bool
	datachannel  bool
}

func (r *Receive) Help() string {
	return "Run receiver pipeline"
}

func (r *Receive) Exec(cmd string, args []string) error {
	fs := flag.NewFlagSet("receive", flag.ExitOnError)
	fs.StringVar(&r.localAddr, "local", "127.0.0.1", "Local address")
	fs.StringVar(&r.remoteAddr, "remote", "127.0.0.1", "Remote address")
	fs.UintVar(&r.roqMapping, "roq-mapping", 0, "RTP mapping to QUIC. 0: datagrams, 1: stream per packet, 2: single stream")
	fs.BoolVar(&r.roqServer, "roq-server", false, "Use RoQ server transport")
	fs.BoolVar(&r.roqClient, "roq-client", false, "Use roQ client transport")
	fs.BoolVar(&r.gstCCFB, "gst-ccfb", false, "Send CCFB RTCP Feedback packets generated by the screamrx Gstreamer element")
	fs.BoolVar(&r.qlog, "log-quic", false, "Log quic internal events")
	fs.BoolVar(&r.nadaFeedback, "nada-feedback", false, "Send NADA feedback")
	fs.BoolVar(&r.traceRTP, "trace-rtp-recv", false, "Log incoming RTP packets")
	fs.BoolVar(&r.datachannel, "dc", false, "Send/Receive data with data channels")

	// swap default values
	flags.SwapRTCPDefaults()

	flags.RegisterInto(fs, []flags.FlagName{
		flags.RTPPortFlag,
		flags.RTCPSendPortFlag,
		flags.RTCPRecvPortFlag,
		flags.RTPFlowIDFlag,
		flags.RTCPRecvFlowIDFlag,
		flags.RTCPSendFlowIDFlag,
		flags.NadaFeedbackFlowIDFlag,
		flags.DataChannelFlowIDFlag,
	}...)

	fs.IntVar(&UDPRecvBufferSize, "recv-buffer-size", UDPRecvBufferSize, "UDP receive 'buffer-size' of Gstreamer udpsrc element")

	DefaultStreamSinkFactory.ConfigureFlags(fs)

	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, `Run a receiver pipeline

Usage:
	%v receive [flags]

Flags:
`, cmd)
		fs.PrintDefaults()
		fmt.Fprintln(os.Stderr)
	}
	fs.Parse(args)

	if len(fs.Args()) > 1 {
		fmt.Fprintf(os.Stderr, "error: unknown extra arguments: %v\n", flag.Args()[1:])
		fs.Usage()
		os.Exit(1)
	}

	if r.roqMapping > 2 {
		fmt.Fprintf(os.Stderr, "Invalid %v value, must be 0, 1 or 2\n", r.roqMapping)
		fs.Usage()
		os.Exit(1)
	}

	if (r.datachannel || r.qlog || r.nadaFeedback || r.roqMapping != 0) && !(r.roqServer || r.roqClient) {
		fmt.Fprintf(os.Stderr, "Flag -%v, -%v, -%v and -%v only valid for RoQ\n", "dc", r.qlog, "nada-feedback", "roq-mapping")
		fs.Usage()
		os.Exit(1)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	for _, p := range []uint{
		flags.RTCPRecvPort,
		flags.RTCPSendPort,
		flags.RTPPort,
	} {
		if p > math.MaxUint32 {
			return fmt.Errorf("invalid port number: %v", p)
		}
	}
	if r.roqClient && r.roqServer {
		return errors.New("cannot run RoQ server and client simultaneously")
	}

	var err error
	r.receiver, err = gstreamer.NewRTPBin()
	if err != nil {
		return err
	}

	r.sink, err = DefaultStreamSinkFactory.MakeStreamSink("rtp-stream-sink", 96)
	if err != nil {
		return err
	}

	if r.roqServer || r.roqClient {
		err = r.setupRoQ(ctx)
	} else {
		err = r.setupUDP()
	}
	if err != nil {
		return err
	}
	return r.receiver.Run()
}

func (r *Receive) setupRoQ(ctx context.Context) error {
	quicOptions := []quictransport.Option{
		quictransport.WithRole(quictransport.Role(r.roqServer)),
		quictransport.SetLocalAddress(r.localAddr, flags.RTPPort), // TODO: which port to use?
		quictransport.SetRemoteAddress(r.remoteAddr, flags.RTPPort),
	}

	if r.nadaFeedback {
		feedbackDelta := time.Duration(20 * time.Millisecond)
		quicOptions = append(quicOptions, quictransport.EnableNADAfeedback(feedbackDelta, uint64(flags.NadaFeedbackFlowID)))
	}

	if r.qlog {
		quicOptions = append(quicOptions, quictransport.EnableQLogs("./receiver.qlog"))
	}

	quicConn, err := quictransport.New(ctx, []string{roqALPN}, quicOptions...)
	if err != nil {
		return err
	}

	roqTransport, err := roq.New(ctx, quicConn.GetQuicConnection())
	if err != nil {
		return err
	}

	dcTransport := quicConn.GetQuicDataChannel()

	// set handlers for datagrams and streams
	// have to forward it ether to roq or dc
	quicConn.HandleDatagram = func(flowID uint64, dgram []byte) {
		roqTransport.HandleDatagram(dgram)
	}
	quicConn.HandleUintStream = func(flowID uint64, rs *quic.ReceiveStream) {
		if flowID == uint64(flags.RTPFlowID) || flowID == uint64(flags.RTCPRecvFlowID) || flowID == uint64(flags.RTCPSendFlowID) {
			roqTransport.HandleUniStreamWithFlowID(flowID, roqProtocol.NewQuicGoReceiveStream(rs))
			return
		}

		if r.datachannel {
			dcTransport.ReadStream(context.Background(), rs, flowID)
			return
		}

		panic(fmt.Sprint("unknown stream flowID ", flowID))
	}

	// start handler
	quicConn.StartHandlers()

	if r.datachannel {
		// setup data channel receiver
		// quic transports has to be started before
		dcReceiver, err := dcTransport.AddDataChannelReceiver(uint64(flags.DataChannelFlowID))
		if err != nil {
			return err
		}

		dataSink, err := data.NewSink(dcReceiver)
		if err != nil {
			return err
		}

		go dataSink.Run()
	}

	rtpSrc, err := roqTransport.NewReceiveFlow(uint64(flags.RTPFlowID), r.traceRTP)
	if err != nil {
		return err
	}
	if err = r.receiver.AddRTPSink(0, r.sink); err != nil {
		return err
	}
	if err = r.receiver.ReceiveRTPStreamFrom(0, rtpSrc, r.gstCCFB); err != nil {
		return err
	}

	rtcpSink, err := roqTransport.NewSendFlow(uint64(flags.RTCPSendFlowID), roq.SendMode(r.roqMapping), false)
	if err != nil {
		return err
	}
	if err = r.receiver.SendRTCPForStream(0, rtcpSink); err != nil {
		return err
	}

	rtcpSrc, err := roqTransport.NewReceiveFlow(uint64(flags.RTCPRecvFlowID), false)
	if err != nil {
		return err
	}
	if err = r.receiver.ReceiveRTCPFrom(rtcpSrc); err != nil {
		return err
	}
	return nil
}

func (r *Receive) setupUDP() error {
	rtpSrc, err := gstreamer.NewUDPSrc(
		r.localAddr,
		uint32(flags.RTPPort),
		gstreamer.EnabelUDPSrcPadProbe(r.traceRTP),
		gstreamer.SetReceiveBufferSize(UDPRecvBufferSize),
	)
	if err != nil {
		return err
	}
	if err = r.receiver.AddRTPSink(0, r.sink); err != nil {
		return err
	}
	if err = r.receiver.ReceiveRTPStreamFromGst(0, rtpSrc.GetGstElement(), r.gstCCFB); err != nil {
		return err
	}

	rtcpSink, err := gstreamer.NewUDPSink(r.remoteAddr, uint32(flags.RTCPSendPort))
	if err != nil {
		return err
	}
	if err = r.receiver.SendRTCPForStreamGst(0, rtcpSink.GetGstElement()); err != nil {
		return err
	}

	rtcpSrc, err := gstreamer.NewUDPSrc(r.localAddr, uint32(flags.RTCPRecvPort))
	if err != nil {
		return err
	}
	if err = r.receiver.ReceiveRTCPFromGst(rtcpSrc.GetGstElement()); err != nil {
		return err
	}
	return nil
}
