//go:build cgo

package subcmd

import (
	"context"
	"flag"
	"fmt"
	"net"
	"os"

	nethttp "net/http"

	"github.com/julienschmidt/httprouter"
	"github.com/mengelbart/mrtp/cmdmain"
	"github.com/mengelbart/mrtp/data"
	"github.com/mengelbart/mrtp/gstreamer"
	"github.com/mengelbart/mrtp/http"
	"github.com/mengelbart/mrtp/webrtc"
)

func init() {
	cmdmain.RegisterSubCmd("webrtc", func() cmdmain.SubCmd { return new(WebRTC) })
}

type WebRTCCodecParameters struct {
	MimeType    string
	ClockRate   uint32
	PayloadType uint8
}

var WebRTCExtraCodecs = []WebRTCCodecParameters{}

type WebRTC struct {
	localAddr        string
	remoteAddr       string
	localPort        string
	remotePort       string
	offer            bool
	gstCCFB          bool
	bwe              string
	maxTargetRate    uint
	traceOutgoingRTP bool
	traceIncomingRTP bool
	datachannel      bool
	dcSourceFile     string
	dcStartDelay     uint
	dcChunks         bool
	pionCCFB         bool
	pionTWCC         bool
	pionReports      bool
	pionNACK         bool
	pionReadCCFB     bool
	sendVideoTrack   bool
	pacing           bool
}

// Help implements cmdmain.SubCmd.
func (w *WebRTC) Help() string {
	return "Run webrtc peer"
}

func (w *WebRTC) Exec(cmd string, args []string) error {
	fs := flag.NewFlagSet("webrtc", flag.ExitOnError)
	fs.StringVar(&w.localAddr, "local", "127.0.0.1", "Local address")
	fs.StringVar(&w.remoteAddr, "remote", "127.0.0.1", "Remote address")
	fs.BoolVar(&w.gstCCFB, "gst-ccfb", false, "Send CCFB RTCP Feedback packets generated by the screamrx Gstreamer element")
	fs.StringVar(&w.bwe, "bwe", "", "Set a bandwidth estimator by name, e.g. 'nada' or 'gcc'")
	fs.UintVar(&w.maxTargetRate, "max-target-rate", 30_000_000, "Set the maximum target rate of the congestion controller in bits per second")
	fs.BoolVar(&w.traceOutgoingRTP, "trace-rtp-send", false, "Log outgoing RTP packets")
	fs.BoolVar(&w.traceIncomingRTP, "trace-rtp-recv", false, "Log incoming RTP packets")

	fs.StringVar(&w.localPort, "local-port", "8080", "Local port of HTTP signaling server to listen on")
	fs.StringVar(&w.remotePort, "remote-port", "8080", "Remote Port of HTTP signaling server to connect to")

	fs.BoolVar(&w.offer, "offer", false, "Act as the offerer for WebRTC signaling")
	fs.BoolVar(&w.pionCCFB, "pion-ccfb", false, "Send RTCP CCFB packets generated by Pion")
	fs.BoolVar(&w.pionTWCC, "pion-twcc", false, "Send RTCP TWCC packets generated by Pion")
	fs.BoolVar(&w.pionReports, "pion-reports", false, "Send RTCP SR/RR packets generated by Pion")
	fs.BoolVar(&w.pionNACK, "pion-nack", false, "Send RTCP NACK packets generated by Pion")
	fs.BoolVar(&w.pionReadCCFB, "pion-read-ccfb", false, "Let Pion read incoming CCFB reports")
	fs.BoolVar(&w.sendVideoTrack, "send-track", false, "Send a media track to the peer")

	fs.BoolVar(&w.datachannel, "dc", false, "Send/Receive data with data channels")
	fs.StringVar(&w.dcSourceFile, "dc-source", "", "File to be sent. If empty, random data will be sent.")
	fs.UintVar(&w.dcStartDelay, "dc-start-delay", 0, "Start delay in seconds before data channel source starts sending data.")
	fs.BoolVar(&w.dcChunks, "dc-chunks", false, "Send chunks on datachannel")

	fs.BoolVar(&w.pacing, "pacing", false, "Enable packet pacing")

	DefaultStreamSinkFactory.ConfigureFlags(fs)
	DefaultStreamSourceFactory.ConfigureFlags(fs)

	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, `Run a WebRTC pipeline

Usage:
	%v webrtc [flags]
`, cmd)
		fs.PrintDefaults()
		fmt.Fprintln(os.Stderr)
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	pipeline, err := gstreamer.NewRTPBin()
	if err != nil {
		return err
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	signaler := webrtc.NewHTTPClientSignaler(fmt.Sprintf("http://%v:%v", w.remoteAddr, w.remotePort))

	stdnet, err := webrtc.NewNet(webrtc.SetRecvBufferSize(10_000_000)) // 10MB
	if err != nil {
		return err
	}
	webrtcOptions := []webrtc.Option{
		webrtc.SetNet(stdnet),
		webrtc.SetSRTPBufferLimit(10_000_000), // 10MB
		webrtc.RegisterDefaultCodecs(),
		webrtc.OnTrack(func(receiver *webrtc.RTPReceiver) {
			sink, newSinkErr := DefaultStreamSinkFactory.MakeStreamSink("rtp-stream-sink", int(receiver.PayloadType()))
			if newSinkErr != nil {
				panic(err)
			}
			if pipelineErr := pipeline.AddRTPSink(0, sink); pipelineErr != nil {
				panic(pipelineErr)
			}
			if pipelineErr := pipeline.ReceiveRTPStreamFrom(0, receiver, w.gstCCFB); pipelineErr != nil {
				panic(pipelineErr)
			}
			if pipelineErr := pipeline.ReceiveRTCPFrom(receiver.RTCPReceiver()); pipelineErr != nil {
				panic(pipelineErr)
			}
		}),
	}

	if w.traceIncomingRTP {
		webrtcOptions = append(webrtcOptions, webrtc.EnableRTPRecvTraceLogging())
	}
	if w.traceOutgoingRTP {
		webrtcOptions = append(webrtcOptions, webrtc.EnableRTPSendTraceLogging())
	}
	if w.pionCCFB {
		webrtcOptions = append(webrtcOptions, webrtc.EnableCCFB())
	}
	if w.pionTWCC {
		webrtcOptions = append(webrtcOptions, webrtc.EnableTWCC())
	}
	if w.pionNACK {
		webrtcOptions = append(webrtcOptions, webrtc.EnableNACK())
	}
	if w.pionReports {
		webrtcOptions = append(webrtcOptions, webrtc.EnableRTCPReports())
	}
	if w.pionReadCCFB {
		webrtcOptions = append(webrtcOptions, webrtc.EnableCCFBReceiver())
	}
	if w.pacing {
		webrtcOptions = append(webrtcOptions, webrtc.EnablePacing())
	}
	if w.bwe != "" {
		bweFactory, exists := BWEFactories[w.bwe]
		if !exists {
			return fmt.Errorf("unknown BWE factory: %v", w.bwe)
		}
		bwe, err := bweFactory.MakeBWE(BWEConfig{
			InitTargetRate: initTargetRate,
			MinTargetRate:  minTargetRate,
			MaxTargetRate:  w.maxTargetRate,
		})
		if err != nil {
			return err
		}
		webrtcOptions = append(webrtcOptions, webrtc.SetBWE(bwe))
	}

	connectedCtx, cancelConnectedCtx := context.WithCancel(context.Background())
	webrtcOptions = append(webrtcOptions, webrtc.OnConnected(func() {
		cancelConnectedCtx()
	}))

	if len(WebRTCExtraCodecs) > 0 {
		for _, c := range WebRTCExtraCodecs {
			webrtcOptions = append(webrtcOptions, webrtc.AddExtraCodecs(c.MimeType, c.ClockRate, c.PayloadType))
		}
	}

	transport, err := webrtc.NewTransport(
		signaler,
		w.offer,
		webrtcOptions...,
	)
	if err != nil {
		return err
	}
	signalingHandler := webrtc.NewHTTPSignalingHandler(transport)
	router := httprouter.New()
	router.HandlerFunc("POST", "/candidate", withCORS(nethttp.HandlerFunc(signalingHandler.HandleCandidate)))
	router.HandlerFunc("OPTIONS", "/candidate", withCORS(nil))
	router.HandlerFunc("POST", "/session_description", withCORS(nethttp.HandlerFunc(signalingHandler.HandleSessionDescription)))
	router.HandlerFunc("OPTIONS", "/session_description", withCORS(nil))

	host := net.JoinHostPort(w.localAddr, w.localPort)
	s, err := http.NewServer(
		http.H1Address(host),
		http.ListenH2(false),
		http.ListenH3(false),
		http.RedirectH1ToH3(false),
		http.Handle(router),
	)
	if err != nil {
		return err
	}
	go func() {
		if listenErr := s.ListenAndServe(); listenErr != nil {
			panic(listenErr)
		}
	}()

	if w.offer && w.datachannel {
		dcSender := transport.NewDataChannelSender("data")
		var dataSource *data.DataBin
		dataSource, err = createDataSource(dcSender, w.dcSourceFile, w.dcStartDelay, false, w.dcChunks)
		if err != nil {
			return err
		}
		go func() {
			if sourceErr := dataSource.Run(ctx); sourceErr != nil {
				fmt.Printf("failed to run data source: %v\n", sourceErr)
			}
		}()
	} else if w.datachannel {
		dcReceiver := transport.NewDataChannelReceiver()
		var dataSink *data.DataSink
		dataSink, err = data.NewSink(dcReceiver)
		if err != nil {
			return err
		}
		go func() {
			if sinkErr := dataSink.Run(); sinkErr != nil {
				fmt.Printf("failed to run data sink: %v\n", sinkErr)
			}
		}()
	}

	if w.sendVideoTrack {
		var source gstreamer.RTPSourceBin
		source, err = DefaultStreamSourceFactory.MakeStreamSource("rtp-stream-source")
		if err != nil {
			return err
		}

		var rtpSink *webrtc.RTPSender
		rtpSink, err = transport.AddLocalTrackWithCodec(source.EncodingName())
		if err != nil {
			return err
		}
		if err = pipeline.AddRTPTransportSink(0, rtpSink); err != nil {
			return err
		}

		// set callback of transport, so CCs can set the target rate of the encoder
		ba, ok := source.(BitrateAdapter)
		if ok {
			transport.SetTargetRate = ba.SetBitrate
		}

		// TODO(ME): Cannot enable SCReAM here because WebRTC rewrites the SSRCs
		// of outgoing packets. Thus, the sender cannot use the feedback,
		// because the receiver will mirror the SSRC set by Pion and not the one
		// seen by the ScreamTx implementation.
		// Another problem in the current ScreamRx implementation is that it
		// does not correctly set the CCFB type (count value of the RTCP
		// header). Pion expects the correct type, otherwise it can't forward
		// the packet to the correct SSRC (because it cannot read the media SSRC
		// from a raw RTCP packet. The ScreamTx sender on the other hand,
		// expects the type set to 0.
		if err = pipeline.AddRTPSourceStreamGst(0, source); err != nil {
			return err
		}
		if err = pipeline.ReceiveRTCPFrom(rtpSink.RTCPReceiver()); err != nil {
			return err
		}
	} else {
		if err = transport.AddRemoteVideoTrack(); err != nil {
			return err
		}
	}

	if err = pipeline.SendRTCPForStream(0, transport); err != nil {
		return err
	}

	<-connectedCtx.Done()
	return pipeline.Run()
}

func withCORS(next nethttp.Handler) func(w nethttp.ResponseWriter, r *nethttp.Request) {
	return func(w nethttp.ResponseWriter, r *nethttp.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*") // lock to your origin in production
		w.Header().Set("Access-Control-Allow-Methods", "POST, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
		if r.Method == nethttp.MethodOptions {
			w.WriteHeader(nethttp.StatusNoContent)
			return
		}
		if next == nil {
			w.WriteHeader(nethttp.StatusOK)
			return
		}
		next.ServeHTTP(w, r)
	}
}
