// Package media defines the boundary between media pipelines and transports.
//
// A media pipeline (GStreamer, gopipe, ...) produces and consumes RTP packets.
// A transport (RoQ, WebRTC, UDP, ...) moves them. Neither needs to know the
// other's type: a pipeline is handed plain io.ReadCloser / io.WriteCloser
// endpoints, and every implementation registers itself under a name so that
// commands can select one at run time.
//
// This package must stay free of cgo, so that command wiring builds (and CI
// compiles) without GStreamer or the native codecs present.
package media

import (
	"context"
	"io"

	"github.com/mengelbart/mrtp"
)

// Reserved media locations. Only SinkDiscard is a reserved word: every other
// non-empty location is a file to read from or write to, so a file literally
// named "discard" has to be given a path ("./discard").
const (
	// SourceTest is the SourceLocation asking for the pipeline's generated
	// test source. It is empty, so a command that is given no source sends
	// generated media. Not every pipeline has a test source.
	SourceTest = ""
	// SinkDisplay is the SinkLocation asking for the media to be rendered. It
	// is empty, so a command that is given no sink renders. Not every pipeline
	// can render.
	SinkDisplay = ""
	// SinkDiscard is the SinkLocation asking for the media to be dropped once
	// it is decoded.
	SinkDiscard = "discard"
)

// RTCPFlow carries the RTCP endpoints belonging to one RTP stream. Either
// direction may be nil if the transport does not provide it, in which case the
// pipeline must not generate or expect RTCP on that side.
type RTCPFlow struct {
	// Send receives the RTCP packets generated by the pipeline.
	Send io.WriteCloser
	// Recv delivers the RTCP packets received from the peer.
	Recv io.ReadCloser
}

// RateBounds are the bitrate bounds of the congestion controller, in bits per
// second. Only a pipeline that runs its own congestion control needs them
// (GStreamer's screamtx does). A pipeline whose rate is steered from outside,
// through Sender.SetTargetBitrate, ignores them.
type RateBounds struct {
	Initial uint
	Min     uint
	Max     uint
}

// SenderConfig describes one outgoing stream.
type SenderConfig struct {
	// Name identifies the stream for logging and for naming pipeline elements.
	Name string

	Codec       mrtp.Codec
	PayloadType int

	// SourceLocation is the file to read media from, or SourceTest for the
	// pipeline's generated test source.
	SourceLocation string

	// RTP receives the RTP packets produced by the pipeline.
	RTP  io.WriteCloser
	RTCP RTCPFlow

	RateBounds RateBounds
}

// ReceiverConfig describes one incoming stream.
type ReceiverConfig struct {
	// Name identifies the stream for logging and for naming pipeline elements.
	Name string

	Codec       mrtp.Codec
	PayloadType int

	// SinkLocation is the file to write media to, SinkDisplay to render, or
	// SinkDiscard to drop the media.
	SinkLocation string

	// RTP delivers the RTP packets received from the peer.
	RTP  io.ReadCloser
	RTCP RTCPFlow
}

// Sender is a running outgoing stream.
type Sender interface {
	// SetTargetBitrate sets the encoder's target bitrate in bits per second.
	// Pipelines whose source cannot adapt return nil without doing anything.
	SetTargetBitrate(uint) error
}

// Pipeline is one media pipeline implementation. A single Pipeline can carry
// several streams in both directions, because some implementations (notably
// GStreamer's rtpbin) share state between them and must be driven by a single
// Run.
//
// Streams may be added before or while Run is executing: WebRTC only learns
// about an incoming stream once the remote track arrives.
type Pipeline interface {
	// AddSender adds an outgoing stream and returns a handle for rate control.
	AddSender(SenderConfig) (Sender, error)

	// AddReceiver adds an incoming stream. It returns no handle, because
	// nothing in the codebase steers a receiver after it is set up.
	AddReceiver(ReceiverConfig) error

	// Run drives the pipeline until the media ends, ctx is cancelled, or an
	// error occurs. It blocks. A pipeline with no sender runs until cancelled.
	Run(ctx context.Context) error

	// Close releases the pipeline's resources. It is safe to call after Run
	// has returned.
	Close() error
}
