// Package flags implements command-line flags for mrtp.
//
// The design idea is taken from [upspin.io/flags], but most of the code is
// modified. This package uses a slightly modified version of [RegisterInto] and
// the internal [flags]-map. See [Upspin LICENSE] for upspins copyright and
// license information.
//
// [upspin.io/flags]: https://github.com/upspin/upspin/tree/334f107fe3d98225d7adfbb35b74e066fbca9875/flags
// [Upspin LICENSE]: https://github.com/upspin/upspin/blob/334f107fe3d98225d7adfbb35b74e066fbca9875/LICENSE
package flags

import (
	"flag"
	"fmt"
)

type FlagName string

// flag keys
const (
	LocalAddrFlag  FlagName = "local"
	RemoteAddrFlag FlagName = "remote"
	HTTPAddrFlag   FlagName = "http-address"
	HTTPSAddrFlag  FlagName = "https-address"

	RTPPortFlag      FlagName = "rtp-port"
	RTCPRecvPortFlag FlagName = "rtcp-recv-porto"
	RTCPSendPortFlag FlagName = "rtcp-send-porto"

	CertFlag FlagName = "cert"
	KeyFlag  FlagName = "key"

	RoQServerFlag FlagName = "roq-server"
	RoQClientFlag FlagName = "roq-client"

	GstCCFBFlag FlagName = "gst-ccfb"

	SendVideoFileFlag FlagName = "file"

	SinkTypeFlag FlagName = "sink-type"
	LocationFlag FlagName = "location"

	TraceRTPRecvFlag FlagName = "trace-rtp-recv"
	TraceRTPSendFlag FlagName = "trace-rtp-send"
)

// default values
const (
	defaultAddr      = "127.0.0.1"
	defaultHTTPAddr  = "127.0.0.1:8080"
	defaultHTTPSAddr = "127.0.0.1:4443"

	defaultCert = "localhost.pem"
	defaultKey  = "localhost-key.pem"

	defaultRTPPort      = uint(5000)
	defaultRTCPSendPort = uint(5001)
	defaultRTCPRecvPort = uint(5002)

	defaultSendVideoFile = "videotestsrc"

	defaultSinkType = uint(0) // Corresponds to autovideosink
)

// Flag vars
var (
	// LocalAddr
	LocalAddr = defaultAddr

	// RemoteAddr
	RemoteAddr = defaultAddr

	// HTTP Server
	HTTPAddr = defaultHTTPAddr

	HTTPSAddr = defaultHTTPSAddr

	Cert = defaultCert

	Key = defaultKey

	// RTP Receive Port
	RTPPort = defaultRTPPort

	RTCPRecvPort = defaultRTCPRecvPort

	RTCPSendPort = defaultRTCPSendPort

	RoQServer = false

	RoQClient = false

	GstCCFB = false

	SendVideoFile = defaultSendVideoFile

	SinkType = defaultSinkType

	Location = ""

	TraceRTPRecv = false

	TraceRTPSend = false
)

type flagVar func(*flag.FlagSet)

func stringVar(p *string, name FlagName, defaultValue *string, usage string) func(*flag.FlagSet) {
	return func(fs *flag.FlagSet) {
		fs.StringVar(p, string(name), *defaultValue, usage)
	}
}

func uintVar(p *uint, name FlagName, defaultValue *uint, usage string) func(*flag.FlagSet) {
	return func(fs *flag.FlagSet) {
		fs.UintVar(p, string(name), *defaultValue, usage)
	}
}

func boolVar(p *bool, name FlagName, defaultValue *bool, usage string) func(*flag.FlagSet) {
	return func(fs *flag.FlagSet) {
		fs.BoolVar(p, string(name), *defaultValue, usage)
	}
}

var flags = map[FlagName]flagVar{
	// Address related flags
	LocalAddrFlag:  stringVar(&LocalAddr, LocalAddrFlag, &LocalAddr, "Address for local servers"),
	RemoteAddrFlag: stringVar(&RemoteAddr, RemoteAddrFlag, &RemoteAddr, "Address for remote servers"),
	HTTPAddrFlag:   stringVar(&HTTPAddr, HTTPAddrFlag, &HTTPAddr, "HTTP Server address"),
	HTTPSAddrFlag:  stringVar(&HTTPSAddr, HTTPSAddrFlag, &HTTPSAddr, "HTTPS Server address"),

	RTPPortFlag:      uintVar(&RTPPort, RTPPortFlag, &RTPPort, "UDP Port number for outgoing RTP stream"),
	RTCPRecvPortFlag: uintVar(&RTCPRecvPort, RTCPRecvPortFlag, &RTCPRecvPort, "UDP port for incoming RTCP stream"),
	RTCPSendPortFlag: uintVar(&RTCPSendPort, RTCPSendPortFlag, &RTCPSendPort, "UDP port for outgoing RTCP stream"),

	// TLS Certificate
	CertFlag: stringVar(&Cert, CertFlag, &Cert, "TLS Certificate"),
	KeyFlag:  stringVar(&Key, KeyFlag, &Key, "TLS Certificate key"),

	// RoQ Flags
	// TODO: Add separate flags for RoQ flow ids
	RoQServerFlag: boolVar(&RoQServer, RoQServerFlag, &RoQServer, "Use RoQ server transport. Port flags are used as flow IDs"),
	RoQClientFlag: boolVar(&RoQClient, RoQClientFlag, &RoQClient, "Use RoQ client transport. Port flags are used as flow IDs"),

	// CC flags
	GstCCFBFlag: boolVar(&GstCCFB, GstCCFBFlag, &GstCCFB, "Send CCFB RTCP Feedback packets generated by the screamrx Gstreamer element"),

	// IO Flags
	SendVideoFileFlag: stringVar(&SendVideoFile, SendVideoFileFlag, &SendVideoFile, "Which video to send"),
	SinkTypeFlag:      uintVar(&SinkType, SinkTypeFlag, &SinkType, "Sink type (0: autovideosink, 1: filesink, requires <location> to be set)"),
	LocationFlag:      stringVar(&Location, LocationFlag, &Location, "Location for filesink if <sink-type> is 1 (filesink)"),

	// tracing flags
	TraceRTPRecvFlag: boolVar(&TraceRTPRecv, TraceRTPRecvFlag, &TraceRTPRecv, "Log incoming RTP packets"),
	TraceRTPSendFlag: boolVar(&TraceRTPSend, TraceRTPSendFlag, &TraceRTPSend, "Log outgoing RTP packets"),
}

func RegisterInto(fs *flag.FlagSet, names ...FlagName) {
	if len(names) == 0 {
		for _, f := range flags {
			f(fs)
		}
	} else {
		for _, n := range names {
			f, ok := flags[n]
			if !ok {
				panic(fmt.Sprintf("unknown flag: %q", n))
			}
			f(fs)
		}
	}
}
